CREATE TABLE IF NOT EXISTS images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  file_id TEXT NOT NULL,
  chat_id TEXT NOT NULL,
  short_code TEXT UNIQUE NOT NULL,
  expire_at TIMESTAMP,
  tags TEXT,
  filename TEXT,
  size INTEGER,
  visit_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  file_id TEXT,
  type TEXT, -- upload, visit
  ip TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);